/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    CommentRow: typeof import('./src/components/commentRow.vue')['default']
    Edit: typeof import('./src/components/edit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/tabbar.vue')['default']
    User: typeof import('./src/components/user.vue')['default']
    View: typeof import('./src/components/view.vue')['default']
  }
}

// For TSX support
declare global {
  const Card: typeof import('./src/components/card.vue')['default']
  const CommentRow: typeof import('./src/components/commentRow.vue')['default']
  const Edit: typeof import('./src/components/edit.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Tabbar: typeof import('./src/components/tabbar.vue')['default']
  const User: typeof import('./src/components/user.vue')['default']
  const View: typeof import('./src/components/view.vue')['default']
}